# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    automerge:
      enable: true
      allow:
        - dependency-type: "production"
        - update-type: "minor"
        - update-type: "patch"

  - package-ecosystem: "github-actions" 
    directory: "/.github" 
    schedule:
      interval: "daily" 
    open-pull-requests-limit: 10
    automerge:
      enable: true
      allow:
        - dependency-type: "production" 
        - update-type: "minor"
        - update-type: "patch"
